namespace NavBuddy;

public static class GoogleEarthExporter
{
	public static string flightPlanTemplate()
	{
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><kml xmlns=\"http://www.opengis.net/kml/2.2\" xmlns:gx=\"http://www.google.com/kml/ext/2.2\" xmlns:kml=\"http://www.opengis.net/kml/2.2\" xmlns:atom=\"http://www.w3.org/2005/Atom\"><Document><name>@DOCUUMENTNAME@</name><open>1</open><Style id=\"sh_ylw-pushpin\"><IconStyle><scale>1.3</scale><Icon><href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href></Icon><hotSpot x=\"20\" y=\"2\" xunits=\"pixels\" yunits=\"pixels\"/></IconStyle><BalloonStyle></BalloonStyle><LineStyle><color>ff00c000</color><width>4</width></LineStyle><PolyStyle><color>8000c000</color></PolyStyle></Style><Style id=\"sn_ylw-pushpin\"><IconStyle><scale>1.1</scale><Icon><href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href></Icon><hotSpot x=\"20\" y=\"2\" xunits=\"pixels\" yunits=\"pixels\"/></IconStyle><BalloonStyle></BalloonStyle><LineStyle><color>ff00c000</color><width>4</width></LineStyle><PolyStyle><color>8000c000</color></PolyStyle></Style><StyleMap id=\"msn_ylw-pushpin\"><Pair><key>normal</key><styleUrl>#sn_ylw-pushpin</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#sh_ylw-pushpin</styleUrl></Pair></StyleMap><Placemark><name>@NAME@</name><styleUrl>#msn_ylw-pushpin</styleUrl><LineString><extrude>1</extrude><tessellate>1</tessellate><altitudeMode>absolute</altitudeMode><coordinates>@COORDINATES@</coordinates></LineString></Placemark></Document></kml>";
	}

	public static string trackTemplate()
	{
		return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><kml xmlns=\"http://www.opengis.net/kml/2.2\" xmlns:gx=\"http://www.google.com/kml/ext/2.2\" xmlns:kml=\"http://www.opengis.net/kml/2.2\" xmlns:atom=\"http://www.w3.org/2005/Atom\"><Document><name>@DOCUUMENTNAME@</name><open>1</open><Style id=\"sh_ylw-pushpin\"><IconStyle><scale>1.3</scale><Icon><href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href></Icon><hotSpot x=\"20\" y=\"2\" xunits=\"pixels\" yunits=\"pixels\"/></IconStyle><BalloonStyle></BalloonStyle><LineStyle><color>ff00c000</color><width>2</width></LineStyle><PolyStyle><color>8000c000</color></PolyStyle></Style><Style id=\"sn_ylw-pushpin\"><IconStyle><scale>1.1</scale><Icon><href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href></Icon><hotSpot x=\"20\" y=\"2\" xunits=\"pixels\" yunits=\"pixels\"/></IconStyle><BalloonStyle></BalloonStyle><LineStyle><color>ff00c000</color><width>2</width></LineStyle><PolyStyle><color>8000c000</color></PolyStyle></Style><StyleMap id=\"msn_ylw-pushpin\"><Pair><key>normal</key><styleUrl>#sn_ylw-pushpin</styleUrl></Pair><Pair><key>highlight</key><styleUrl>#sh_ylw-pushpin</styleUrl></Pair></StyleMap><Placemark><name>@NAME@</name><styleUrl>#msn_ylw-pushpin</styleUrl><LineString><extrude>1</extrude><tessellate>1</tessellate><altitudeMode>absolute</altitudeMode><coordinates>@COORDINATES@</coordinates></LineString></Placemark></Document></kml>";
	}
}
